service: chatApp

provider:
  name: aws
  region: ap-southeast-2
  runtime: provided.al2
  lambdaHashingVersion: 20201221

plugins:
  - ./vendor/bref/bref

functions:
  responder:
    handler: chat_app.php
    description: ""
    layers:
      - ${bref:layer.php-80}

# Exclude files from deployment
package:
  patterns:
    - "!tests/**"
