org: glo12345
app: portfolio-backend
service: portfolio-backend
unresolvedVariablesNotificationMode: error

provider:
  name: aws
  region: ap-southeast-2
  environment:
    NODE_ENV: dev

plugins:
  - serverless-dotenv-plugin
  - serverless-plugin-typescript
  - serverless-offline

custom:
  dotenv:
    path: config/.env
  serverless-offline:
    httpPort: 9000

package:
  patterns:
    - '!config/.env.**'
    - '!tests/**'

functions:
  # Main flag checking function
  checkFlag:
    runtime: nodejs12.x
    handler: app/handler.checkFlag
    events:
      - http:
          method: POST
          path: /check

  # Book Challenge functions

  # Search book by name
  searchBookByName:
    runtime: nodejs12.x
    handler: app/handler.searchBook
    events:
      - http:
          method: POST
          path: /c4/searchbook

  # Php Challenge
  # sendChatMessage:
  #   runtime: php8.x
