org: glo12345
app: portfolio-backend
service: portfolio-backend

provider:
  name: aws
  environment:
    NODE_ENV: dev

plugins:
  - serverless-plugin-typescript
  - serverless-offline

custom:
  serverless-offline:
    httpPort: 9000

package:
  exclude:
    - config/.env.stg
    - config/.env.pro
  include:
    - config/.env.dev

functions:
  # Main flag checking function
  checkFlag:
    runtime: nodejs12.x
    handler: app/handler.checkFlag
    events:
      - http:
          method: POST
          path: /check

  # Book Challenge functions

  # Search book by name
  searchBookByName:
    runtime: nodejs12.x
    handler: app/handler.searchBook
    events:
      - http:
          method: POST
          path: /c4/searchbook

  # Php Challenge
  # sendChatMessage:
  #   runtime: php8.x
