org: glo12345
app: portfolio-backend
service: portfolio-backend

provider:
  name: aws
  region: 'ap-southeast-2'
  lambdaHashingVersion: '20201221'
  environment:
    NODE_ENV: dev

plugins:
  - serverless-plugin-typescript
  - serverless-offline

custom:
  serverless-offline:
    httpPort: 9000

package:
  patterns:
    - '!config/.env*'
    - 'config/.env.dev'

functions:
  # Main flag checking function
  checkFlag:
    runtime: nodejs14.x
    handler: app/handler.checkFlag
    events:
      - http:
          method: POST
          path: /checkFlag

  checkRoute:
    runtime: nodejs14.x
    handler: app/handler.checkRoute
    events:
      - http:
          method: GET
          path: /checkRoute
          cors: true

  # Book Challenge functions
  # Search book by name
  searchBookByName:
    runtime: nodejs14.x
    handler: app/handler.searchBook
    events:
      - http:
          method: POST
          path: /c4/searchbook
          cors: true

  

  # Php Challenge
  # sendChatMessage:
  #   runtime: php8.x
